package com.example.crapmap;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button userSelectButton = findViewById(R.id.user_select_button);
        Button toiletListButton = findViewById(R.id.toilet_list_button);
        Button profileButton = findViewById(R.id.profile_button);
        Button mapButton = findViewById(R.id.map_button);

        userSelectButton.setOnClickListener(this);
        toiletListButton.setOnClickListener(this);
        profileButton.setOnClickListener(this);
        mapButton.setOnClickListener(this);
    }

    //    @Override
    public void onClick(View view) {
        // user select -> launch user select view
        // TODO
        if (view.getId() == R.id.user_select_button) {
            Log.d("MainActivity.java", "clicked user select button");
            // Intent intent = new Intent(this, UserSelect.class /*fix this*/);
            // startActivity(intent);
        }

        // toiletListButton -> launch toilet list view
        // TODO
        if (view.getId() == R.id.toilet_list_button) {
            Log.d("MainActivity.java", "clicked toilet list button");
            Intent intent = new Intent(this, ToiletList.class);
            Log.d("MainActivity.java", "AAAAAAAAAAAA");
            startActivity(intent);
        }

        // profileButton -> launch profile view
        // TODO


        // mapButton -> launch map view
        // TODO

    }

    // auto-generated by android studio, idk
    @Override
    public void onPointerCaptureChanged(boolean hasCapture) {
        super.onPointerCaptureChanged(hasCapture);
    }
}